---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  maxHistory: 3
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: metrics-server
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: admin
      interval: 10m
  values:
    replicas: 2

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    rbac:
      create: true
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
