---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: admin
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/metrics-server
