---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-podmonitor
  namespace: admin
  labels:
    prometheus: prometheus-kube-cluster
spec:
  namespaceSelector:
    matchNames:
      - tooling
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
