---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: echoserver
  namespace: admin
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`echoserver.fr-production.miniature-fiesta.ml`)
    priority: 10
    services:
    - kind: Service
      name: echoserver
      namespace: admin
      port: 80
      scheme: http
