---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: echoserver-round-robin
  namespace: admin
  labels:
    ingress: traefik
spec:
  weighted:
    services:
      - name: echoserver-a
        port: 80
        weight: 3
      - name: echoserver-b
        port: 80
        weight: 1
