---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgAfDGQyipFxOe8iLLVSzduTSQ9ss4J67GcMbcOEizLcHYva6saZ32DqiEeheNXve+IZwzuZAbUYgILZQINpK5sHpGwud6Kg1glbh1bRw7Ufp8JFEHh0j5cem8O8/g+0QMYCrF30ZZ7JEDh3poGpcsWmiD56j2jbyDbCe5dx2vjyXP2o8iDCz3CmIJH8EoKkEsP6l2cq24mkil/MroS5tV2m2HGjvDRKaVX62VmHJHolEtDUzzE/hrhwapPQ3IWW+rKE/iE6QRhN71voNSNzLYySiSklBrjlgTAIC97dwZ42shFMU3BfgCDb2nNXJq4sDY4SJJ6eCF8iZwKy0avWhOl5kt1er1fFC+d5lScLMWZBeWnafH57UU/zz2dEXvNveMFRI5X64319dPjGvEMg/Q8TglPnwvSXMC1gmlPoK92JZwnbBQwOWLqgo8AkKy7PrH/tl+jX8tohp209FDagL0PwiBQXQ3CGYnHctNKJ9mtG8S/93y/3awV+e34XHTU29OsvnnXLyD0+s3N96g8d/JxeJCJr3p6+0SG4Nz7ccSg9yZuyueHEWZQ+vSPmysdvMStmUBodJ8afTkZNAAvFLcv4m7NcxCgXyGX4D5bR9l3w5eJUotQrfMT11IW+uQ9tLGXYhjsGkaxhh+0L2s8OsD0nlwkTb6XZBSx4yob+Ro/4oXu6xczS2wLpF4RLE7vKywcX/6qw8P95r2zJeYbfuyJyO8meI2GrhBI8sPDGPToIeEp9dYhVtBqy3UuBZ57XSxrOVTDoTlDJEm+u7MiFs24NLkiS5oejPuF754TJnBqs3qB5nY6Wi7rC9U+RvzuXJwEdpOQcDJWielW8PkqPL6qJ4EwMkbLS7xZ77Qc3IguWRX9zTleONIaOs+aDj0+ZzL02SRKCry4/CSvzklzZUNk3rlP4Nzs3LjwxJVFeDDNlLtPiQq6ZONVvhnvSbFkIvfBGX+aAy3iz0aRKSqDOxX4QZdMC8Jbyuz2vWB07qkkJ0EluqMofmcsau4An9dRzaeaKRft1Zc7IQxNyQTsF74g/FVZ0MTqoWgDnR2i/
  template:
    metadata:
      name: thanos-objstore
      namespace: monitoring

