---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgDCqIMhSdoSN7e1lv97z0ELMn/2sNFE0LWjHyUPj6GRVNt0qFLVV2CcDmq7CW87tX6neX2foxiJtWPekxYQjeuzLTAsBskvfQD/1+CYpVyQhe4oOrqBsfwcYTyFp7AG7QPEiUJuAHiNlv8ddUqqzCfccgNUARu70K5leNgZHKAy/6aCVnNwZsSBVcULYef2DAZX2dfvZhLNhJyy3pgtfpWpMkh4UOD/bs0evJeEPJOBQjwT5HJyKwkLbWV6HSVNigwwaopSVQV8EhSbdFnpS5PNAVY7Bx1iFfVkKTjx/1X4T9H2rSv4TPMmEvo9scbOPhnw+ObwlgNk25SdEh/Yz1/1SMRuS1Q74ConBoKmDDEv5X/EzR/mh8NAFSi5/7aiLE8Et2HE/Td0MsqsW4127LLKB09O8Iu2vNerR2rEC5QpYkrAdW50y2siA1fLARi0D7nefbLc5745VuTpOv1xgZ/2bS2Cuij9po/rZOjNAo4xjx1uPdq4ktSuBnhSDgRPMaYJ5ia/cKH0mCVD1c4eaDfWDcQiZZgIiSn3IDW2WIPJrFKUPgdhE2Hl0WKC21taBokp+46BxsJWodjBZFwbpNhnMYEQ5lKyR8cN+UNz0ZOcv1wOIuakkMAj4G5T+uJJ+dCO2BrmPpwm6P3qo02I+QPSDW0/aXZa+R9hKeQLnOUepUbu6Hw8Rd1Fd/ZeSyDxXLeOSQska92zzcz7vGG6WpAle/oCzuHSs4SDwaE/8Tubgkzu1GCPBr+KqylSxqWhNwUd5IOrqlCaZ1uhbfykkQ2w0IXARqGCxC6zSULEEGskq+9RswLDPxSm84p+rIoHvhPNMGj/J/53qnIs4TP2wsmSdGG8FYumke8vt86n3bTiSp2jtjTWQLYMzadlBpjOVykkIlYoIxqhhFAW7qYqA2pEOe3XUyCwtSuiR6oLIJrRWlwHZuKnIcvoXMZUQ9Q4C7iS4PCmit0cGz+hqo3vynubjr+f7bwRU/k0nlzArdTpp6WR7u2EpVSVad884ak+9i8MjzoCCxiKkWM=
  template:
    metadata:
      name: thanos-objstore
      namespace: monitoring
