---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgClupO02SmaLmXfm5XVIyLGmjphyCZHK3dtALGFMsxCbu70/6/vyh63e7Txfc8DbbKjnsKFdEd1VQ3bPYOSqdiCQx9LvcYG68BmcUX2IrjU1XDSpt9LFXBb2CGxJ8R2YcuT7Xp+BaybPl1RZHc4xsQxwBO8BTeLitmwumnXbeWgDnevt7WT2MHIY2tfzQSFVgrS9VtgMJL6WxJgB/LkBXp+iYmZupQX6gAr8CjrxVskoPPRTUDB14hGgtaAfAXpXUNLhe6SG+CE30Y3xUqWrKo07tDbc05tKiEjlFkErHikh7fWO2mwgpF+VHSIp5t1utct8X19fMnacMj/v7mqA3obyat2r1UygL81RMdin8VjBPohmpfRQkOGeRMAPJyD0JZL+awevQI3QGhyTBE7DqjQNMRVxXQ1ip69ho5BMoxNfXw5FKw8NfwRIWIdR38RqGCQ6J4YSg/ARcOz+B/J8lfdlsLwCIEIaNkRS+YCdOevmn7UTN+HOJFVeTciD5xMviQjAQUePltkvgTq90iIvrFgB1EqJrrcYH9ZU7fP6Kve/GhxUTAcWYA7/sQSNVx/U0EOnSrZ+MqWXO5fdEg/VGnbD2tKFyNBYphyXUzSetjEq0tng2ISLNDibMEF3XJfoN3o5uHZi24/ueKny0iFXr8TQGSGMfXva8Hbv28rL5Wvdgx3ih55VLByqxn3CjphCxnk9L3CgcOmEezvZZxLeVSb9Ln2B1IyX2ffNYFT7op9s/qWs8PAmz6idnkFtHiMmXox3EaWICXX5NcQgCehomOeMSNbrfXxetZiRPGfCFlq8p65z3oYbq4Ro2FkeyLqpJ0h+J28yzGVnR/WIeLZjVOc8HFxrmzyPAhgwVl+5UpuDpiszCNHo9nkys+bKqgZqeV1jMHLrnyR43oFjDJA4HdecVLj+wLPUVhRvRtgCeBxDYR2y+4v+XHmJXQMQyo6B+xNLwIgrAN4LTy18iDrDKrlj4dNtNCbtJo0pcjvQQ==
  template:
    metadata:
      name: thanos-objstore
      namespace: monitoring

