---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgCGy0rIUnTmj9iUsv63fSfYbF1wJf7I5xcjfE2wNjDtVqnMmSnGx358Tmu0cb9ddaCKGOcER1kBFbvf+8DcgMdDR+u1AjMw/oC2Amfu+OCZPz9XieTRWAUd+HoMRgzZrexWv93Qs0vy5BwO5/YIHYPcxJKyfwzmrnLdU2DOIQdj/pKJ6wMznOsdw7Zie3bARkaS66ovWcCtiucbA0XZN44cx9raeXEbz+T6Dv8PlwK74b7o9yT5rZk6gr3uVUZw2Esg3+YIYhqcI6n/VEoDz59BKIiE6ZApcBPWegk8Cgz2l9VElx4LCOjfk6AGqMGpkSpPba6Y8Wn/gMXlp1+Yls760v1r0NNdhqoRrHZ9wXOdPmcdLGh+SdOq5WIwOcqoj4R0CW69jHJRdkAWn/uanr/R8/NPxAc73StzDXe+1DnuIHZUnoAvTpzaMZ0k9cM81t25dbOeZ/hi0QwrpM5xSA0FwcoJGqe9LulCVY4FxSKr+yEnjzthNu7oo9Q3rsHjUUJek9qLwSQaHqN4jti0rfqAds6DdASJgPKNzBJDpP8XYW5SD2iPdYxpjuPfMFnRqU6vIDKki5hJsOjC0r+nH7XAqRcDdhmCsvL8gmTndwytCxDZwHBbvLdqZ0zUHjb7Z8fAohDLa0GjNzSvqu6svVyRSH9DFLtU2ESdkz8bjwuCJSlGE67HKNxV1kszYsHkHdTpAgiVc9Blrte0XIeY7hv4DiyESLIfV8vCWeVkts7mwjiYAGY+ZzcjxkgsKaG5VYLlIoIYgwTyHu+kOkAl7MN70QVvsYpVbIROcYKSKoONbIf4lKswD7g4PZMBESxjs4T3rvde+yPXipQqTcupyf3j/e1Pk8bTOpPDnp9wYHAYedBRu4SLiOGuTAhJKAeqk8FyNZkcIxkefKoJxNfG8HVUCXxxHF37RIilDJxVSbZY566cW/SOpM5tg58ltxOwMdjVYs72ir9lNqiCmcYvDiCU8zA7rjNfGM3Ng2J+GiPSseCXhhAvyt/7HIXeaN7BAjlwvi/fywkBaQrJ
  template:
    metadata:
      name: thanos-objstore
      namespace: monitoring

