---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgCeCc6r0Znh+n3GZnJL0xW409pDinv6ZdLALaXIXq1fvwlkX7LcQGSFdE5jTbUlRC3SMPNaLaRM32vZEErb4NTt37fzA3h8uIvpmD4qCzTVHsFdtmqG82PTCC1i5Yy5I6pFSQKlTPD1zmAlBc187XO+MAtbRz5PoE3ZZyQdJbsK1J1E7Y3O/FJgDn0Bzvjbrw4kX4vAqPnMIjON1yKDxrjF+aTOka0ZwKxtfwhnd4t2AlPJe/HBXt1xlyeWbkGGsr/J7NPj/KfdHciKToTYf8CUhthfFcRTfhg+R5gTRf5sfVWVhZKuKbUSYKjnVz2rOiHTweHmTqHRUds3WjUxSFSdV9qH5DuOec/yfZNTjOrC5SoZS1YGlKdHL1pUbsk/+6p0wgvWAfKZquAC29tE1iFCBTGuRyf1FrydpH3LjC+nRD7EJXlrksPG3eOg0VraADaGTGZirAN9NXamVYsyiEqjTW9hnJFqfPGgM8eI/NS+pwqLRZYL4jTvOqswbDjgva+acwp/WeI9XsG5CC3fckWrWBbrqgtALkmSnmZ3TxDLBcwgCtq96/Vranxdoup4lITkEYvAfb9dsOlHDigZGUbOiogzoyM+4syHKpdmN9WS+F6Z2dMEkW0ULZI2bzPkhtXU8PdWLiTR0VMBBTLuTp1USEh+AEOv+ZB6DMWCqml2E/5FquZjfqfd+dR6ZpiuGQJDiey+qiynxTfKZeVLfxK1JM3xUYfrbybzfmS+62OBRnu4v+thLq9Siera0K3hkw6MVxRU+Y7hSSPUTyfYzXArlgHjVKaPO8LcmtCbhVWGA3X+/rsSpK6k1ZvnBqhoByf5XMOrARrqSeYwfSWNH+fp/wCuyVfiiVcXJVp9Bm1td9YcPKpEEdZRmcyMpHkrWz3hRsa5kZyCf0UD+QG0IkNvb5IuLQ+yiW66lX2Th4NnnK2kqj2ifDjPV6e/DfieJOAovfOaE1AMIOj8DmHFblJlXuPIGXEbaq1L9oL/fw==
  template:
    metadata:
      name: thanos-objstore
      namespace: monitoring

