---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-hubble
  namespace: kube-system
spec:
  releaseName: cilium-hubble
  maxHistory: 3
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: cilium
      version: 1.12.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: admin
      interval: 10m
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
