---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: externaldns
  namespace: ingress
spec:
  interval: 5m
  maxHistory: 2
  releaseName: externaldns
  chart:
    spec:
      chart: external-dns
      version: 1.12.1
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: externaldns
        namespace: admin
  values:
    provider: scaleway

    sources:
      - service
      - ingress
      - crd

    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --request-timeout=60s

    domainFilters:
      - fr-production.miniature-fiesta.ml
    logFormat: json
    logLevel: info
    interval: 10m

    txtPrefix: "externaldns."

    env:
      - name: SCW_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: externaldns-credentials
            key: access-key
      - name: SCW_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: externaldns-credentials
            key: secret-key
      - name: SCW_DEFAULT_ORGANIZATION_ID
        value: "32cfc40b-5d06-4dc5-a8fd-f6759a1c8889"

    resources:
      requests:
        memory: 128Mi
        cpu: 200m
      limits:
        memory: 128Mi
        cpu: 200m
