apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: botty-uptime
  namespace: admin
spec:
  encryptedData:
    botty-uptime: AgBWbPkgXky4CMNyWlM2LJ281CmdLyXb3sIJ2Q4pVSvn6PCPJeVMVAGHKh8SGgay9VwLbpnOBQEqyyKilnL+ha7ReXozTU6j5KrGFJrLqodHpLsDpSLvkOa3n2aetOr+BSd0rDoMNeFBISiFPMNV4wvJm4qN3LkPvF9hSf2DvsBShs2JCkuCS93HOgTzEP9v6MZp1iVb6KB1A1tew3OsATkpbvtDy11wA3q+RVuHlqxxzoE8O95vWCUeHVowtWWYr/ubAJe7eUpBfhT5ADYHIacQu7zbDOYNU1zokdCJqh3AErWNx/zHPQskEu4PjM4kBuCbFpew95MpFBjI1hLfjaFc/IC+6Vqjy4v1HjQf4RWKUgy4l4kzjkVABW4VkoleZxyXTOApO0bA3dU60MfiusGCSpyu0t3XQXOruzUsb+RUEhl+eVsInRVYXCkvls/VmL+kyGYOicaDxOhnopQXFnPV1eZO0T7rFlWfOo+TiB2oV6zuycwFZ0zB9RCRvvZUo1sXqKcGoQYGDC+cXI1351+kKIEnLOh6Gj5d5qULuyXSdlCAqLPEGrn11VArEWqdUxQ+ZNrWLQgmzIl/HP1hGoQCgzeZfPa63mdkBKf0MUJMXfGileTNvoREQ1U5gt9wsRBecpP9VM/5a29Yt8jYLHop3Cj7tgssYSaOPnlqLR5BZxGTcEBzcCAJWTfN5cieWUi/M1WjDixAdhHkal7RCWkyaDXJx9XNUxTiqDVTucUm0BCAXIMUR3dEmfy3tOng0k4/iIZ3CvCZrU14+f3oLIK51qW9+xtFlxL8OrohFRJ6Fb5DJQBADt41CVBeUpjk422N0+w73vKmoAye/wgLgXhp5TF36EWH0oHp1KBZVSPrXyYfXBQHqXkSXlUB0oNx1Gd/zbCHg/PqkJS2NhZPuOUi+PfImrKFndQUhf8BtPN3u2p9RfMsTs9xkZfdoMnIvXEzc1hm9wSFKUcK8kf3nsrkINs1EpFF3cOAGxxWCMpIJ5spLdtw4xxySCv/p/gC5GFrUPzCqBFiXL5CKe1DQ1+i04RZ3Ov8RNyVRo1lkazFu8l+Bq86LtQ3gXIi/3s47LUTZLpKXVoVRVHChnvI/SNLjP1+NH7/J7AJtr/Bd24QsOQF88Ldl5B8PiDwBmwLd+6tz6MUbg8cSfu+oK4UDSOJfXUtUQbk41Z4WV+PyujCc4htwFoAPD6+w9TjxD019Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: botty-uptime
      namespace: admin

